# Generated by Django 3.0.7 on 2020-06-16 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('venue', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
                ('match_type', models.CharField(blank=True, choices=[('50', '50 Overs'), ('20', '20 Overs'), ('10', '10 Overs'), ('35', '35 Overs'), ('90', '90 Overs'), ('test5', '5 Days Test'), ('test3', '3 Days Test')], default='', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=50)),
                ('age_group', models.CharField(blank=True, choices=[('u10', 'Under 10'), ('u12', 'Under 12'), ('u14', 'Under 14'), ('u16', 'Under 16'), ('u19', 'Under 19'), ('u23', 'Under 23'), ('open', 'Open Age')], default='', max_length=6, null=True)),
                ('venue', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('match_type', models.CharField(blank=True, choices=[('50', '50 Overs'), ('20', '20 Overs'), ('10', '10 Overs'), ('35', '35 Overs'), ('90', '90 Overs'), ('test5', '5 Days Test'), ('test3', '3 Days Test')], default='', max_length=5, null=True)),
                ('total_teams', models.IntegerField()),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('runner_up', models.CharField(blank=True, max_length=50, null=True)),
                ('best_batsman', models.CharField(blank=True, max_length=50, null=True)),
                ('best_bowler', models.CharField(blank=True, max_length=50, null=True)),
                ('best_fielder', models.CharField(blank=True, max_length=50, null=True)),
                ('best_player', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('overs_bowled', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('man_of_the_match', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Not Mentioned', max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('batting_hand', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='Not Mentioned', max_length=5, null=True)),
                ('batting_order', models.CharField(blank=True, choices=[('opener', 'Opener'), ('middle', 'Middle Order'), ('finish', 'Finisher'), ('tail', 'Tail Ender')], default='Not Mentioned', max_length=6, null=True)),
                ('bowling_hand', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='Not Mentioned', max_length=5, null=True)),
                ('bowling_type', models.CharField(blank=True, choices=[('RAF', 'Right Arm Fast'), ('RAM', 'Right Arm Medium'), ('LAF', 'Left Arm Fast'), ('LAM', 'Left Arm Medium'), ('RAFS', 'Right Arm Finger Spin'), ('RAWS', 'Right Arm Wrist Spin'), ('LAFS', 'Left Arm Finger Spin'), ('LAWS', 'Left Arm Wrist Spin')], default='Not Mentioned', max_length=5, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Tournament'),
        ),
    ]
