# Generated by Django 3.0.7 on 2020-06-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('match_type', models.CharField(blank=True, choices=[('50', '50 Overs'), ('20', '20 Overs'), ('10', '10 Overs'), ('35', '35 Overs'), ('90', '90 Overs'), ('test5', '5 Days Test'), ('test3', '3 Days Test')], default='', max_length=5, null=True)),
                ('total_teams', models.IntegerField()),
                ('winner', models.CharField(max_length=50)),
                ('runner_up', models.CharField(max_length=50)),
                ('best_batsman', models.CharField(max_length=50)),
                ('best_bowler', models.CharField(max_length=50)),
                ('best_fielder', models.CharField(max_length=50)),
                ('best_player', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('venue', models.CharField(max_length=20)),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('overs_bowled', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('match_type', models.CharField(blank=True, choices=[('50', '50 Overs'), ('20', '20 Overs'), ('10', '10 Overs'), ('35', '35 Overs'), ('90', '90 Overs'), ('test5', '5 Days Test'), ('test3', '3 Days Test')], default='', max_length=5, null=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Tournament')),
            ],
        ),
    ]
