# Generated by Django 3.0.7 on 2020-06-14 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_tournament_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='balls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fours',
        ),
        migrations.RemoveField(
            model_name='match',
            name='overs_bowled',
        ),
        migrations.RemoveField(
            model_name='match',
            name='runs_conceded',
        ),
        migrations.RemoveField(
            model_name='match',
            name='runs_scored',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sixes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wickets',
        ),
        migrations.AddField(
            model_name='match',
            name='place',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='place',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='best_batsman',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='best_bowler',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='best_fielder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='best_player',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='runner_up',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='venue',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('overs_bowled', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('man_of_the_match', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
