# Generated by Django 3.0.7 on 2020-06-11 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Not Mentioned', max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('batting_hand', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='Not Mentioned', max_length=5, null=True)),
                ('batting_order', models.CharField(blank=True, choices=[('opener', 'Opener'), ('middle', 'Middle Order'), ('finish', 'Finisher'), ('tail', 'Tail Ender')], default='Not Mentioned', max_length=6, null=True)),
                ('bowling_hand', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='Not Mentioned', max_length=5, null=True)),
                ('bowling_type', models.CharField(blank=True, choices=[('RAF', 'Right Arm Fast'), ('RAM', 'Right Arm Medium'), ('LAF', 'Left Arm Fast'), ('LAM', 'Left Arm Medium'), ('RAFS', 'Right Arm Finger Spin'), ('RAWS', 'Right Arm Wrist Spin'), ('LAFS', 'Left Arm Finger Spin'), ('LAWS', 'Left Arm Wrist Spin')], default='Not Mentioned', max_length=5, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
