# Generated by Django 3.0.7 on 2020-06-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='age_group',
            field=models.CharField(blank=True, choices=[('u10', 'Under 10'), ('u12', 'Under 12'), ('u14', 'Under 14'), ('u16', 'Under 16'), ('u19', 'Under 19'), ('u23', 'Under 23'), ('open', 'Open Age')], default='', max_length=6, null=True),
        ),
    ]
