# Generated by Django 3.0.7 on 2020-06-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200614_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='is_not_out',
            field=models.BooleanField(default=0),
        ),
    ]
